# Generated by Django 3.2.5 on 2021-07-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuizTitle', models.CharField(max_length=100)),
                ('time', models.IntegerField(help_text='Duration of the Quiz')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.TextField()),
                ('CorrectOption', models.TextField()),
                ('OtherOption1', models.TextField()),
                ('OtherOption2', models.TextField()),
                ('OtherOption3', models.TextField()),
                ('AuthorKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('QuizKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizHandling.quiz')),
            ],
        ),
    ]
