# Generated by Django 3.2.5 on 2021-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizHandling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.DurationField(help_text='Duration of the Quiz'),
        ),
    ]
