# Generated by Django 3.2.5 on 2021-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizHandling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Time',
            field=models.IntegerField(help_text='Duration of the Quiz in minutes'),
        ),
    ]
