# Generated by Django 3.2.5 on 2021-07-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizHandling', '0002_alter_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Score',
            field=models.IntegerField(default=4, help_text='Score of this question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(blank=True, default=0, help_text='Total score of the Quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.DurationField(help_text='Duration of the Quizin format HH:MM:SS'),
        ),
    ]
